import type { Metadata } from "next";
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { ViewTransitions } from "next-view-transitions";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/src/components/layout/Footer";
import NavBar from "@/src/components/layout/navBar/NavBar";
import { notFound } from "next/navigation";
import { routing } from "@/src/i18n/routing";
import PromotionCard from "@/src/components/layout/PromotionCard";
import Header from "@/src/components/layout/Header";
import Logo from "@/src/components/layout/Logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) return notFound();
  return (
    <ViewTransitions>
      <html lang={locale} className="md:overflow-hidden md:h-full">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased md:overflow-hidden md:h-full `}
        >
          <NextIntlClientProvider>
            <div className="">
              {/* MOBILE */}
              <div className="md:hidden flex flex-col min-h-screen pb-16 pt-20">
                <Header />
                <div className="flex-1">
                  <div className="bg-white dark:bg-black">
                    {children}
                  </div>
                </div>
                <Footer />
                <NavBar typeDisplay="mobile" />
              </div>

              {/* DESKTOP */}
              <div className="hidden md:grid grid-cols-12 h-screen w-full box-border">
                {/* SIDEBAR */}
                <aside className="col-span-2 flex flex-col h-full bg-custom dark:bg-custom border-r border-gray-200 dark:border-gray-700">
                  {/* Logo */}
                  <div className=" h-20 flex items-center justify-center">
                    <Logo />
                  </div>
                  {/* Navigation */}
                  <div className="flex-1 overflow-y-auto py-4 px-3 ">
                    <NavBar typeDisplay="desktop" />
                  </div>
                  {/* Promotion Card */}
                  <PromotionCard />
                </aside>

                {/* MAIN CONTENT */}
                <div className="col-span-10 min-h-0 flex flex-col bg-custom dark:bg-custom">
                  {/* Header */}
                    <Header />
                  {/* Page Content */}
                  <div className="flex-1 overflow-auto min-h-0">
                    <div className="flex flex-col min-h-full">
                      <main className="flex-1">
                        <div className="bg-white dark:bg-black p-6">
                          {children}
                        </div>
                      </main>
                      <div className="px-1">
                        <Footer />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </NextIntlClientProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
